### ISSUE TITLE
"cite" has to work for IEEE as expected

### ISSUE THREAD

**Issue by koppor** [subhramit/jabref#13]
1. I create a new document
2. I select CSL IEEE
3. I write some text
4. I select the entry Katz_2011 in JabRef
5. I click "Cite in-text"
6. `[1]` appears in JabRef
7. I click "Cite"
8. The full reference appears

What is the correct behavior? https://docs.jabref.org/cite/openofficeintegration demnostratates it with another style. Numberics is more complicated.

Let's look at latex:

```latex
Winery~\cite{Winery} is a graphical modeling tool.
The whole idea of TOSCA is explained by \citet{Binz2009}.
```

- `cite` is "cite" button
- `citet` is `cite-in-text` button
- There exist also special latex commands like `\parencite{key1,key2}`, which would be similar to cite in parentheses, which can be found under the `cite special` button.

Output:

![image](https://github.com/user-attachments/assets/c86e5df3-a751-433d-8044-aee56c58202f)

Full LaTeX example at https://github.com/latextemplates/ieee.

Result when using "cite" and "cite-in-text":

![image](https://github.com/user-attachments/assets/170763a6-cf45-4161-80f3-dd2567295643)

Expected output:

--

Note that the description of "Cite special" also gives a hint:

![image](https://github.com/user-attachments/assets/ef2126f7-f548-4df3-9152-00cf5c9686d7)

![image](https://github.com/user-attachments/assets/2ba9e64e-18d4-47a9-834d-6647797bbaf2)

- 1: `[1]` (preceded by a space)
- 2: `Binz et al. [2]` (preceded by a space)
- 3: Only one newline between the entries. Better no new line.

Regarding 2: I know, this is hard. Maybe even not possible. - I would "just" send the authors to JabRef's AuthorFormatter saying: I want to have the last name of the first author and then "et al"

---

I know, I need to craft an example using [Chocolate.bib](https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/Chocolate.bib). #FutureWork

**Comment by koppor** [comment]
Note that the buttons work as expected with JStyle.

![image](https://github.com/user-attachments/assets/3164bff5-bca6-4c64-b6c9-d13d5598c4af)

**Comment by subhramit** [comment]
> * 1: `[1]` (preceded by a space)
> * 2: `Binz et al. [2]` (preceded by a space)
> * 3: Only one newline between the entries. Better no new line.
> 
> Regarding 2: I know, this is hard. Maybe even not possible. - I would "just" send the authors to JabRef's AuthorFormatter saying: I want to have the last name of the first author and then "et al"
> 
> I know, I need to craft an example using [Chocolate.bib](https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/Chocolate.bib). #FutureWork

Task 1:  **On priority.** In-text citations should be preceded by space.
Task 2: **Moving for later.**
Task 3:  **On priority.** Investigate what's causing the newlines (in certain citation styles only).

**Comment by Siedlerchr** [comment]
Number 2 is out of scope, we should not mess with the CSL output, cite proc should be able to handle it

**Comment by koppor** [comment]
Please note that in the current version the buttons are not working as expected.

What you implemented in "Cite in-text" should happen when pressing "Cite".

What you implemented in "Cite" should not happen at all. The bibliography is generated by the "Refresh" button.

**Comment by subhramit** [comment]
> The bibliography is generated by the "Refresh" button.

This was, a confusing convention followed even by JStyles, so I kept it like that for the first version. The tooltip said `"Make sure that the bibliography is up to date"` which I changed to `"Make or update bibliography"` to make it more helpful/relevant. Ideally the button icon should be `+/loop` instead of just loop. Optionally, do you want me to move the make bibliography function to the "Cite" button for both jstyle and csl? (note that in jstyle it has a dedicated function already). I am unsure how to make this consistent.

> What you implemented in "Cite in-text" should happen when pressing "Cite".

I did some reading, correct me if I am wrong - what happens currently in CSL when we do "Cite in-text" is actually a valid form of in-text citation:
![image](https://github.com/user-attachments/assets/5f79513f-9e7e-48ed-ac0a-83551b9e5f12)

![image](https://github.com/user-attachments/assets/166961b0-2475-45fb-9bba-fff3b5f9d674)
Source: https://guides.library.unr.edu/apacitation/in-textcite#:~:text=What%20Is%20In%2DText%20Citation,method%20of%20in%2Dtext%20citation.

This is valid, in our context, for IEEE as well:
![image](https://github.com/user-attachments/assets/0db8fedc-c82b-4e66-81dd-7fbb805de234)
![image](https://github.com/user-attachments/assets/0273e4ee-6e60-4ca6-aec3-5eb5efff5231)
![image](https://github.com/user-attachments/assets/82d76db2-2fc8-4a3c-8bc1-cc3219ff03ea)
Source : https://www.scribbr.com/ieee/ieee-in-text-citation/
This is exactly how our "Cite in-text" works (for both single/grouped entries).
More (as sent my @Siedlerchr ) - https://libguides.unf.edu/citationguide/Intext, parenthetical in-text citations (https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/parenthetical-versus-narrative).

If we don't agree to go with this, I can disable the "Cite in-text" button for CSL and move its functionality to "Cite". Then, we may need an additional button for adding individual bibliography (the way Cite works now) (this is absent in JStyles).

**Comment by koppor** [comment]
> > The bibliography is generated by the "Refresh" button.
> This was, a confusing convention followed even by JStyles, 

No.

2. Open LibreOffice
3. LibreOffice: Create new document
5. JabRef: Open Chocolate.bib
1. JabRef: Select JStyle
4. JabRef: connect to libreoffice
5. JabRef: Select "Corti et al."
6. JabRef: Click on "Cite"
7. JabRef: Click on button "Regenerate"

![grafik](https://github.com/user-attachments/assets/5bdf6ec5-a76e-46f2-9781-a84e0b69ddbf)


> so I kept it like thAT FOR THE FIRST VERSION. The tooltip said `"Make sure that the bibliography is up to date"` which I changed to `"Make or update bibliography"` to make it more helpful/relevant. 

This is OK to guide first-time users.

Please rename to "Create or update reference list". I think "reference list" is more clear to newcomers, since they might confuse "bibliography" with something inside JabRef.

> Ideally the button icon should be `+/loop` instead of just loop. 

No.

- A) It should be "+" when there is no bibliography and "loop'" when there is one
- B) It should be a bibliography or list icon

For B, I found 

![grafik](https://github.com/user-attachments/assets/b87484d2-11fe-4764-a5bc-e4eda12a4718)

It is called `format-list-numbered`. See https://devdocs.jabref.org/code-howtos/custom-svg-icons.html for background information of how to include.

> Optionally, do you want me to move the make bibliography function to the "Cite" button for both jstyle and csl? (note that in jstyle it has a dedicated function already). I am unsure how to make this consistent.

No. The bibliography generating/updating functionality has nothing to do with the bibliography.

> > What you implemented in "Cite in-text" should happen when pressing "Cite".
> I did some reading, correct me if I am wrong

I have more than 20 years experience in that. And jstyle implementation is right.

> If we don't agree to go with this, I can disable the "Cite in-text" button for CSL and move its functionality to "Cite". 

Please do that.

> Then, we may need an additional button for adding individual bibliography (the way Cite works now) (this is absent in JStyles).

Please give me one reason why the "Make or create bibliography" button does not cover the use cases of researchers. Until that: Do not add such a button.

**Comment by koppor** [comment]
This is cite:

![grafik](https://github.com/user-attachments/assets/3a08765e-13d1-4d8c-a8b8-cd4305752d43)

This is cite in-text:

![grafik](https://github.com/user-attachments/assets/caa47eda-1e18-4f89-b45b-cae6b784729f)

Background: See https://github.com/subhramit/jabref/issues/13#issue-2448271192 for the latex equivalents `\cite` and `\citet`.

**Comment by subhramit** [comment]
> Please give me one reason why the "Make or create bibliography" button does not cover the use cases of researchers. Until that: Do not add such a button.

Right, I did think it does not make sense to have that. I think I was confused about what "Cite" should do in case of CSL (back when we did not have bibliography generation), and that felt like a way.

**Comment by koppor** [comment]
Fixed with 1b72f946c29c3b2dc623bf86abaf6145b1569da3

**Comment by ThiloteE** [comment]
> Please rename to "Create or update reference list". I think "reference list" is more clear to newcomers, since they might confuse "bibliography" with something inside JabRef.

"References are used to document and substantiate statements made in the paper.

APA publications and other publishers and institutions using APA Style generally require reference lists, not bibliographies. A reference list contains works that specifically support the ideas, claims, and concepts in a paper; in contrast, a bibliography provides works for background or further reading and may include descriptive notes (e.g., an annotated bibliography)."

Source: https://apastyle.apa.org/style-grammar-guidelines/references/lists-vs-bibliographies


Going by that definition, bibliography is more fitting, because it encompases a wider use case. I argue, all reference lists are bibliographies, but not all bibliographies are reference lists.<br>

When it comes to JabRef specifically, there is nothing in JabRef that coincides with the word "bibliography". Things that come close are bibtex, biblatex and library. That's it. It is fine to us bibliography.

**Comment by koppor** [comment]
> > Please rename to "Create or update reference list". I think "reference list" is more clear to newcomers, since they might confuse "bibliography" with something inside JabRef.
> "References are used to document and substantiate statements made in the paper.

I assume following main use case:

The user of JabRef writes a scientific paper.

In my 20+ years experience, papers list only cited references in the "Bibliography", which makes it a "Reference List". Therefore, JabRef (w/ JStyles activated) uses "References" as title, not "Bibliography".

Only the "Insert empty citation" allows the user to derivate from the use case to write clean scientific paper.

Therefore, I proposed "reference list" and not "bibliography"

**Comment by ThiloteE** [comment]
You are pointing to the difference between what JabRef offers as a whole and how JabRef is largely used in practice. We cannot know exactly without surveys, statistics and telemetry, but yes I would agree that the large share of our users **probably** use it for scientific papers, hence setting "References" as default is fine by me, because I assume it eases the workflow of the majority.

For the record:

Other alternatives:
A) have a setting for both --> requires much more coding effort
B) split the header from the main body and let users fill the header manually --> Less "magic". Users have to do research about how to call their list of preferences/bibliography and also may forget to add a header.
